/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BPII_ders1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BurakGulsen
 */
public class UnvanİslemlerSilme extends javax.swing.JFrame {

    /**
     * Creates new form UnvanİslemlerSilme
     *
     */
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("BPII_ders1PU");
    DefaultTableModel dtm = new DefaultTableModel();

    public UnvanİslemlerSilme() {
        initComponents();
        tabloU.setModel(dtm);
        dtm.setColumnIdentifiers(new String[]{"Unvan Sicil Numarası ", "Unvan"});
        tabloyaYansıt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     *
     */
    public boolean Unvankntrl() {
        boolean VarMı = false;
        EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("SELECT u FROM Unvan u");
        List<Unvan> unvanlar = q1.getResultList();
        for (Unvan u : unvanlar) {
            if (u.getUnvanId().equals(Integer.parseInt(txtUId.getText()))) {
                VarMı = true;
            }
        }

        return VarMı;
    }

    public boolean unvanDefaultKntrl() {
        boolean dogruMu = false;
      /*  EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("SELECT u FROM Unvan u");
        List<Unvan> unvanlar = q1.getResultList();
        for (int i=0; i< unvanlar.size();i++) {
       
            if (unvanlar.get(i).getUnvanId().equals(1)) {
                dogruMu = true;
             
              
            }
            
        }*/
       if(Integer.parseInt(txtUId.getText())==1){
           dogruMu=true;
       }
        return dogruMu;
    }
 
        public boolean unvanDefaultKntrl2() {
        boolean dogruMu = false;
      /*  EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("SELECT u FROM Unvan u");
        List<Unvan> unvanlar = q1.getResultList();
        for (int i=0; i< unvanlar.size();i++) {
          
            if (unvanlar.get(i).getUnvanId().equals(2)) {
                dogruMu = true;
                
             
            }
            
        }*/
         if(Integer.parseInt(txtUId.getText())==2){
           dogruMu=true;
       }
        return dogruMu;
    }
          public boolean unvanDefaultKntrl3() {
        boolean dogruMu = false;
      /*  EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("SELECT u FROM Unvan u");
        List<Unvan> unvanlar = q1.getResultList();
        for (int i=0; i< unvanlar.size();i++) {
        
            if (unvanlar.get(i).getUnvanId().equals(3)) {
                dogruMu = true;
                
                
            }
            
        }*/
         if(Integer.parseInt(txtUId.getText())==3){
           dogruMu=true;
       }
        return dogruMu;
    }
      public boolean unvanDefaultKntrl4() {
        boolean dogruMu = false;
       /* EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("SELECT u FROM Unvan u");
        List<Unvan> unvanlar = q1.getResultList();
        for (int i=0; i< unvanlar.size();i++) {
          
            if (unvanlar.get(i).getUnvanId().equals(4)) {
                dogruMu = true;
                
              
            }
            
        }*/
       if(Integer.parseInt(txtUId.getText())==4){
           dogruMu=true;
       }
        return dogruMu; 
       
       
    }
   

    public boolean prsnlUnvanKontrol() {
        boolean varMı = false;
        EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("SELECT p FROM Personel_1 p");
        List<Personel_1> personeller = q1.getResultList();
        for (Personel_1 p : personeller) {
            if (p.getUnvanId().equals(Integer.parseInt(txtUId.getText()))) {
                varMı = true;
            }

        }
        return varMı;
    }
     
    public void unvanSil() {
       try{
        if (Unvankntrl() == true) {
            if (prsnlUnvanKontrol() == true || unvanDefaultKntrl()==true || unvanDefaultKntrl2()== true || unvanDefaultKntrl3()== true || unvanDefaultKntrl4()==true) {
                    JOptionPane.showMessageDialog(null, "Bu unvan Silinemez!", "UYARI", JOptionPane.ERROR_MESSAGE);
                }
             else {
                
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("BPII_ders1PU");
                EntityManager em = emf.createEntityManager();
                Query q = em.createQuery("delete from Unvan u where u.unvanId=:pUnvanId");
                q.setParameter("pUnvanId", Integer.parseInt(txtUId.getText()));
                em.getTransaction().begin();
                q.executeUpdate();
                JOptionPane.showMessageDialog(null, "Unvan başarılı bir şekilde silindi");
                em.getTransaction().commit();
                em.close();
                emf.close();
               
                
            }
    } else {
            JOptionPane.showMessageDialog(null, "Lütfen geçerli sicil numarası girin!", "UYARI", JOptionPane.ERROR_MESSAGE);
        }
       }catch(NumberFormatException e ){
                      JOptionPane.showMessageDialog(null, "Lütfen geçerli sicil numarası girin!", "UYARI", JOptionPane.ERROR_MESSAGE);
                }
       tabloyaYansıt();
}
    public void tabloyaYansıt() {
       dtm.setRowCount(0);
        Connection con = null;
        Statement s = null;
        ResultSet rs = null;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            s = con.createStatement();
            rs = s.executeQuery("select * from unvan");
            while (rs.next()) {
                dtm.addRow(new String[]{rs.getString("UNVAN_ID"), rs.getString("UNVANI")});

            }

        } catch (SQLException ex) {
            Logger.getLogger(UnvanİslemlerSilme.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
  

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eklebtn = new javax.swing.JButton();
        guncelleBtn = new javax.swing.JButton();
        txtUnvan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabloUnvan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        silBtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabloU = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        geriBtn = new javax.swing.JButton();

        eklebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eklebtn.setText("EKLE");
        eklebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklebtnActionPerformed(evt);
            }
        });

        guncelleBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        guncelleBtn.setText("GÜNCELLE");
        guncelleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleBtnActionPerformed(evt);
            }
        });

        txtUnvan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("UNVAN                  :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("UNVAN SİLMEK İÇİN UNVAN ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText(" BÖLÜMÜNÜN DOLDURULMASI YETERLİDİR");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EKLEME İŞLEMİ YAPMAK İSTİYORSAK İLK ÖNCE UNVANIN SİCİL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUMARASINI YAZIP İSTEDİĞİNİZ UNVANIN İSMİNİ YAZIN");

        tabloUnvan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tabloUnvan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabloUnvan);

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        txtID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("UNVAN ID             :");

        silBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        silBtn.setText("SİL");
        silBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silBtnActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("GERİ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        tabloU.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tabloU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabloU);

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LÜTFEN UNVANIN SİCİL NUMARASINI GİRİN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ÜNVAN SİCİL NUMARASI         :");

        txtUId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SİL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        geriBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        geriBtn.setText("GERİ");
        geriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUId, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(geriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUId, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(geriBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guncelleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleBtnActionPerformed

    }//GEN-LAST:event_guncelleBtnActionPerformed

    private void eklebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklebtnActionPerformed

    }//GEN-LAST:event_eklebtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void silBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silBtnActionPerformed

    }//GEN-LAST:event_silBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        unvanSil();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void geriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriBtnActionPerformed
        UnvanİslemleriMenu unv = new UnvanİslemleriMenu();
        unv.setVisible(true);
        unv.setLocationRelativeTo(null);
        unv.pack();
        unv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_geriBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnvanİslemlerSilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnvanİslemlerSilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnvanİslemlerSilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnvanİslemlerSilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnvanİslemlerSilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eklebtn;
    private javax.swing.JButton geriBtn;
    private javax.swing.JButton guncelleBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton silBtn;
    private javax.swing.JTable tabloU;
    private javax.swing.JTable tabloUnvan;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtUId;
    private javax.swing.JTextField txtUnvan;
    // End of variables declaration//GEN-END:variables
}
